### ISSUE TITLE
Issues with plugin - commands not showing in Kick context menu

### ISSUE THREAD

**Issue by BigPapaPeezy** [Sehelitar/Kick.bot#19]
I am able to successfully import and compile the plugin, but after adding a command and saving Streamer.bot, I can never see the new commands under the trigger menu for Kick. I have re-imported the plugin multiple times - the references are in place, no errors in the compile log, etc.

Here is the output from the log that does not look correct:

`[2023-11-20 21:49:50.491 DBG] Exception : System.AggregateException: One or more errors occurred. ---> PusherClient.OperationTimeoutException: Waiting for 'pusher:connection_established' has timed out after 27.00 second(s).
   at PusherClient.Connection.<ConnectAsync>d__21.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PusherClient.Pusher.<ConnectAsync>d__54.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Kick.KickEventListener.<JoinAsync>d__80.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at Kick.Bot.BotEventListener..ctor(KickEventListener listener, Channel channel)
   at Kick.Bot.BotClient.<StartListeningToSelf>d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at ld57c8a67b374d89986d547810294f4e.CPHInline.<<Authenticate>b__4_0>d.MoveNext()
---> (Inner Exception #0) PusherClient.OperationTimeoutException: Waiting for 'pusher:connection_established' has timed out after 27.00 second(s).
   at PusherClient.Connection.<ConnectAsync>d__21.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PusherClient.Pusher.<ConnectAsync>d__54.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Kick.KickEventListener.<JoinAsync>d__80.MoveNext()<---
`

**Comment by Sehelitar** [comment]
Hi 👋

It seems that the Pusher client cannot connect to their US servers. This shouldn't happen, so there might be an external condition to explain that.

* Is your computer using wireless or cabled connection?
* Is your internet connection stable?
* Can you open this website? https://pusher.com/
* Do you have any software that could prevent connections to their servers?
* Is chat working when you're watching a Kick stream?
* Did you already stream on your channel at least once?

**Comment by BigPapaPeezy** [comment]
* Is your computer using wireless or cabled connection?
Wired connection.
* Is your internet connection stable?
Yes, no packet loss, fiber internet, all gigabit.
* Can you open this website? https://pusher.com/
Yes, that site loads just fine.
* Do you have any software that could prevent connections to their servers?
Firewall is not blocking it. Windows Firewall on stream computer is disabled.
* Is chat working when you're watching a Kick stream?
Yes, never had an issue with it.
* Did you already stream on your channel at least once?
Many streams, but not with Streamer.bot running

**Comment by Sehelitar** [comment]
I will close this for now. This problem seems unrelated to the bot itself and there's no other report of it. I couldn't find any information about this error besides the fact that the Pusher client cannot connect to  Pusher's servers.
If anyone have information about this, feel free to reply here.
