### ISSUE TITLE
Getting this Error in my log.

### ISSUE THREAD

**Issue by kledde** [Sehelitar/Kick.bot#31]
[2024-02-19 21:28:19.991 DBG] [Kick] Authentication...
[2024-02-19 21:28:20.468 DBG] [Kick] Connected as theKledde
[2024-02-19 21:28:20.684 DBG] [Kick] Listening events for channel theKledde
[2024-02-19 21:28:21.209 DBG] Exception : System.IO.FileNotFoundException: Could not load file or assembly 'PusherClient, Version=2.2.1.0, Culture=neutral, PublicKeyToken=69ee33421d7cff3d' or one of its dependencies. The system cannot find the file specified.
File name: 'PusherClient, Version=2.2.1.0, Culture=neutral, PublicKeyToken=69ee33421d7cff3d'
   at Kick.KickClient.GetEventListener()
   at Kick.Bot.BotClient.<StartListeningTo>d__13.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at l927674b771948b8945c7852307f3ba5.CPHInline.<<Authenticate>b__4_0>d.MoveNext()

WRN: Assembly binding logging is turned OFF.
To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.
Note: There is some performance penalty associated with assembly bind failure logging.
To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].

[2024-02-19 21:28:29.815 INF] TwitchService :: Connected to Broadcaster EventSub, and authenticated
[2024-02-19 21:28:49.563 FTL] Fatal UI Exception
System.NullReferenceException: Object reference not set to an instance of an object.
   at Kick.Bot.BotEventListener.Finalize()
[2024-02-19 21:28:54.375 DBG] Twitch Service :: 4 users joined, existing (4), new (0)

**Comment by Sehelitar** [comment]
PusherClient.dll seems to be missing in your installation directory. Did you unzip all files from the archive?
