### ISSUE TITLE
after the 0.2.4 update it doesn't work anymore

### ISSUE THREAD

**Issue by luisamanett** [Sehelitar/Kick.bot#73]
i update to 0.2.4  and it doesn't work anymore , no login compare anymore

**Comment by mqtt12** [comment]
unfortunately i don't see a login to kick

**Comment by Sehelitar** [comment]
Hey 👋 

Did you update Kick.bot with the latest version?
You'll find it here : https://github.com/Sehelitar/Kick.bot/releases/latest

This is mandatory with every major update of Streamer.bot.

**Comment by mqtt12** [comment]
I have the current stremerbot 0.2.4 and the version on it https://github.com/Sehelitar/Kick.bot/releases/latest

**Comment by Sehelitar** [comment]
Please provide a log file (the latest) for further investigation. 🙏 
You can find these in the logs folder.

**Comment by mqtt12** [comment]
[2024-08-17 00:15:55.713 INF] Precompiling inline code
[2024-08-17 00:15:55.713 DBG] InlineCode :: Creating and compiling instance for 'Kick'
[2024-08-17 00:15:55.900 DBG] [Kick] Extension loaded. Starting...
[2024-08-17 00:15:57.287 DBG] [Kick] Authentication...
[2024-08-17 00:15:57.351 DBG] Exception : System.Exception: No data received.
   at Kick.Internal.HostBrowser.<>c__DisplayClass27_0.<ExecuteAsyncFetch>b__0()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from the previous location where the exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Kick.Internal.HostBrowser.<ExecuteAsyncFetch>d__27.MoveNext()
--- End of stack trace from the previous location where the exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Kick.KickClient.<APIGet>d__49`1.MoveNext()
--- End of stack trace from the previous location where the exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Kick.KickClient.<GetCurrentUserInfos>d__2.MoveNext()
--- End of stack trace from the previous location where the exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Kick.KickClient.<Authenticate>d__47.MoveNext()
--- End of stack trace from the previous location where the exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Kick.Bot.BotClient.<Authenticate>d__11.MoveNext()
--- End of stack trace from the previous location where the exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at seb6bf81862849969a421ea785a223e1.CPHInline.<<Authenticate>b__4_0>d.MoveNext()

**Comment by luisamanett** [comment]
I updated it now it works, thanks

**Comment by Sehelitar** [comment]
@mqtt12 Try to remove the ``Streamer.bot.exe.WebView2`` folder from the bot's installation folder before launch. The login window *should* appear again.
